apiVersion: v1
kind: Service
metadata:
  name: {{ include "DomainManager.domain-fault-management.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
      {{- include "DomainManager.labels" . | nindent 4 }}
      {{- with .Values.dfm.service.labels }}
      {{- . | toYaml | nindent 4 }}
      {{- end }}
spec:
  type: {{ .Values.dfm.service.type | default "ClusterIP" }}
  ports:
  - name: dfm-port
    port: {{ .Values.dfm.port | default "8080" }}
    targetPort: dfm-port
  selector:
   {{- include "DomainManager.domain-fault-management.selectorLabels" . | nindent 4 }}