apiVersion: v2
name: cluster-gateway
description: A Helm chart managing entrypoints to services in the cluster
version: 4.8.3
appVersion: 1.9.4
type: application
keywords:
  - "ipm"
  - "nginx-ingress"
  - "gateway"
dependencies:
  - name: ingress-nginx
    version: 4.8.3
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress-nginx.enabled
  - name: external-dns
    version: 6.28.4
    repository: https://charts.bitnami.com/bitnami
    condition: external-dns.enabled

maintainers:
  - name: Madhav Kothapalli
    email: mkothapalli@infinera.com
deprecated: false