# /*
#  * Copyright 2022 Google LLC. 
#  * 
#  * This software is provided as-is, without warranty or representation for any use or purpose. 
#  * Your use of it is subject to your agreement with Google.
#  */
steps:
  - name: '${_PRE_REQ_REGION}-docker.pkg.dev/$PROJECT_ID/saas-cloud-build/saas-cloud-build-${_PREFIX}:latest'
    dir: gcp-deployment/single-tenant/terraform/env/saas/regions/gke-asm-acm-template/
    entrypoint: 'bash'
    env:
      - "_CUSTOMER_NAME=${_CUSTOMER_NAME}"
      - "_APIGEE=${_APIGEE}"
    args:
    - '-c'
    - |
      git fetch > /dev/null 2>&1
      git checkout ${_BRANCH_NAME}
      if [ "${_LB_TYPE}" = "http" ] && [ "${_APIGEE}" = "false" ]; then
        sed -e "s/BUILD_PROJECT_ID/$PROJECT_ID/g" -e "s/CUSTOMER_NAME/${_CUSTOMER_NAME}/g" -e "s/BUILD_ID/$BUILD_ID/g" -e "s/REGION/$$_PRE_REQ_REGION/g" -e "s/FUNCTION_URI/`echo $$_CLOUD_FUNCTION_URI | sed 's#https://##'`/g" script.sh.tpl > script.sh;
        sh script.sh
        rm -rf script.sh
      elif [ "${_LB_TYPE}" = "http" ] && [ "${_APIGEE}" = "true" ]; then
        sed -e "s/BUILD_PROJECT_ID/$PROJECT_ID/g" -e "s/CUSTOMER_NAME/${_CUSTOMER_NAME}/g" -e "s/BUILD_ID/$BUILD_ID/g" -e "s/REGION/$$_PRE_REQ_REGION/g" -e "s/FUNCTION_URI/`echo $$_CLOUD_FUNCTION_URI | sed 's#https://##'`/g" appigee.sh.tpl > appigee.sh;
        sh appigee.sh
        rm -rf appigee.sh
      else
        sed -e "s/BUILD_PROJECT_ID/$PROJECT_ID/g" -e "s/CUSTOMER_NAME/${_CUSTOMER_NAME}/g" -e "s/BUILD_ID/$BUILD_ID/g" -e "s/REGION/$$_PRE_REQ_REGION/g" -e "s/FUNCTION_URI/`echo $$_CLOUD_FUNCTION_URI | sed 's#https://##'`/g" script-tcp.sh.tpl > script-tcp.sh;
        sh script-tcp.sh
        rm -rf script-tcp.sh
      fi
    secretEnv: ['_CLOUD_FUNCTION_URI','_PRE_REQ_REGION']

  - name: '${_PRE_REQ_REGION}-docker.pkg.dev/$PROJECT_ID/saas-cloud-build/saas-cloud-build-${_PREFIX}:latest'
    id: Remove Directory
    entrypoint: 'bash'
    args:
    - '-c'
    - |-
      sed -e "s/CUSTOMER_NAME/$$_CUSTOMER_NAME/g" gcp-deployment/single-tenant/terraform/env/saas/regions/gke-asm-acm-template/setup.py.tpl > gcp-deployment/single-tenant/terraform/env/saas/regions/gke-asm-acm-template/setup.py;
      python3 gcp-deployment/single-tenant/terraform/env/saas/regions/gke-asm-acm-template/setup.py 
      git add .
      if [ -n "$(git status --porcelain)" ]; then
        echo "There are changes";
        git config --global user.email "$$_CUSTOMER_EMAIL"
        git config --global user.name "$$_CUSTOMER_NAME"
        git commit -m "client $$_CUSTOMER_NAME's gke acm deleted"
        git push --set-upstream origin ${_BRANCH_NAME}
      else
        echo "No changes are there";
        exit
      fi
    secretEnv: ['_CUSTOMER_NAME', '_CUSTOMER_EMAIL']
  
  - name: '${_PRE_REQ_REGION}-docker.pkg.dev/$PROJECT_ID/saas-cloud-build/saas-cloud-build-${_PREFIX}:latest'
    entrypoint: 'bash'
    args:
    - '-c'
    - |-
      git config --global user.email "$$_CUSTOMER_EMAIL"
      git config --global user.name "$$_CUSTOMER_NAME"
      mkdir -p gcp-deployment/single-tenant/terraform/env/saas/regions/$$_CUSTOMER_NAME-gke-asm-acm/
      envsubst < gcp-deployment/single-tenant/terraform/env/saas/regions/gke-asm-acm-template/terraform.tfvars > gcp-deployment/single-tenant/terraform/env/saas/regions/$$_CUSTOMER_NAME-gke-asm-acm/terraform.tfvars
      for f in $(find gcp-deployment/single-tenant/terraform/env/saas/regions/gke-asm-acm-template/ -regex '.*\.tf'); do envsubst < $f > "gcp-deployment/single-tenant/terraform/env/saas/regions/$$_CUSTOMER_NAME-gke-asm-acm/$(basename $f)"; done
      git add .
      git commit -m "client $$_CUSTOMER_NAME's gke acm created"
      git push --set-upstream origin ${_BRANCH_NAME}
    secretEnv: ['_CUSTOMER_NAME', '_CUSTOMER_EMAIL', '_CUSTOMER_REGION', 'TF_STATE_BUCKET_NAME', 'CSR_APP_REPO_NAME','PREFIX','LOG_BUCKET_NAME','SEED_PROJECT_ID']

  - name: '${_PRE_REQ_REGION}-docker.pkg.dev/$PROJECT_ID/saas-cloud-build/saas-cloud-build-${_PREFIX}:latest'
    args:
      - '-c'
      - |
        cd gcp-deployment/single-tenant/terraform/env/saas/regions/$$_CUSTOMER_NAME-gke-asm-acm
        terraform init
    id: terraform init
    entrypoint: sh
    secretEnv: ['_CUSTOMER_NAME']

  - name: '${_PRE_REQ_REGION}-docker.pkg.dev/$PROJECT_ID/saas-cloud-build/saas-cloud-build-${_PREFIX}:latest'
    args:
      - '-c'
      - |
        cd gcp-deployment/single-tenant/terraform/env/saas/regions/$$_CUSTOMER_NAME-gke-asm-acm
        terraform fmt
    id: terraform fmt
    entrypoint: sh
    secretEnv: ['_CUSTOMER_NAME']
    
  - name: '${_PRE_REQ_REGION}-docker.pkg.dev/$PROJECT_ID/saas-cloud-build/saas-cloud-build-${_PREFIX}:latest'
    args:
      - '-c'
      - |
        cd gcp-deployment/single-tenant/terraform/env/saas/regions/$$_CUSTOMER_NAME-gke-asm-acm
        terraform validate
    id: terraform validate
    entrypoint: sh
    secretEnv: ['_CUSTOMER_NAME']
  
  - name: '${_PRE_REQ_REGION}-docker.pkg.dev/$PROJECT_ID/saas-cloud-build/saas-cloud-build-${_PREFIX}:latest'
    args:
      - '-c'
      - |
        cd gcp-deployment/single-tenant/terraform/env/saas/regions/$$_CUSTOMER_NAME-gke-asm-acm
        terraform plan
    id: terraform plan
    entrypoint: sh
    secretEnv: ['_CUSTOMER_NAME']
    
  - name: '${_PRE_REQ_REGION}-docker.pkg.dev/$PROJECT_ID/saas-cloud-build/saas-cloud-build-${_PREFIX}:latest'
    args:
      - '-c'
      - |
        cd gcp-deployment/single-tenant/terraform/env/saas/regions/$$_CUSTOMER_NAME-gke-asm-acm
        terraform apply -input=false -auto-approve
    id: terraform apply
    entrypoint: sh
    secretEnv: ['_CUSTOMER_NAME']

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
        gcloud alpha builds triggers run ${_CUSTOMER_NAME}-single-tenant-scheduled-query-saas-trigger --branch=${_BRANCH_NAME} --region $$_CUSTOMER_REGION
    id: 'trigger next build'
    secretEnv: ['_CUSTOMER_REGION']

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_NUMBER/secrets/${_CUSTOMER_NAME}-CUSTOMER_NAME/versions/latest
    env: _CUSTOMER_NAME
  - versionName: projects/$PROJECT_NUMBER/secrets/${_CUSTOMER_NAME}-CUSTOMER_EMAIL/versions/latest
    env: _CUSTOMER_EMAIL
  - versionName: projects/$PROJECT_NUMBER/secrets/${_CUSTOMER_NAME}-CUSTOMER_REGION/versions/latest
    env: _CUSTOMER_REGION
  - versionName: projects/$PROJECT_NUMBER/secrets/${_CUSTOMER_NAME}-TF_STATE_BUCKET_NAME/versions/latest
    env: TF_STATE_BUCKET_NAME
  - versionName: projects/$PROJECT_NUMBER/secrets/${_CUSTOMER_NAME}-LOG_BUCKET_NAME/versions/latest
    env: LOG_BUCKET_NAME
  - versionName: projects/$PROJECT_NUMBER/secrets/${_CUSTOMER_NAME}-SEED_PROJECT_ID/versions/latest
    env: SEED_PROJECT_ID
  - versionName: projects/$PROJECT_NUMBER/secrets/${_CUSTOMER_NAME}-CSR_APP_REPO_NAME/versions/latest
    env: CSR_APP_REPO_NAME
  - versionName: projects/$PROJECT_NUMBER/secrets/${_CUSTOMER_NAME}-PREFIX/versions/latest
    env: PREFIX
  - versionName: projects/$PROJECT_NUMBER/secrets/${_PREFIX}_CLOUD_FUNCTION_URI/versions/latest
    env: _CLOUD_FUNCTION_URI
  - versionName: projects/$PROJECT_NUMBER/secrets/${_PREFIX}_PRE_REQ_REGION/versions/latest
    env: _PRE_REQ_REGION

logsBucket: 'gs://${_LOG_BUCKET_NAME}'
options:
  logging: GCS_ONLY
  workerPool:
    'projects/${_PREFIX}-anthos-hub/locations/${_PRE_REQ_REGION}/workerPools/${_PREFIX}-private-worker-pool'
timeout: 86400s
