apiVersion: v1
kind: ConfigMap
metadata:
  name: xrsimulatorconfig
  labels:
    {{- include "xrpmclient.labels" . | nindent 4 }}
data:
  config.yml: |
    {{- include "xrpmclient.deploymentConfig" . | nindent 4 -}}
