{{- if not (lookup "v1" "Secret" .Release.Namespace "infn-registry") }}
apiVersion: v1
kind: Secret
metadata:
  name: infn-registry
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "xrpmclient.labels" . | nindent 4 }}  
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-10"
    helm.sh/hook-delete-policy: before-hook-creation
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\"}}}" .Values.global.infnRegistry.url .Values.global.infnRegistry.username .Values.global.infnRegistry.password | b64enc | quote }}
{{- end }}  