apiVersion: v1
kind: Service
metadata:
  name: {{ include "DomainManager.network-connection-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
      {{- include "DomainManager.labels" . | nindent 4 }}
      {{- with .Values.ncs.service.labels }}
      {{- . | toYaml | nindent 4 }}
      {{- end }}
spec:
  type: {{ .Values.ncs.service.type | default "ClusterIP" }}
  ports:
  - name: ncs-port
    port: {{ .Values.ncs.port | default "8080" }}
    targetPort: ncs-port
  selector:
   {{- include "DomainManager.network-connection-service.selectorLabels" . | nindent 4 }}