# /*
#  * Copyright 2022 Google LLC. 
#  * 
#  * This software is provided as-is, without warranty or representation for any use or purpose. 
#  * Your use of it is subject to your agreement with Google.
#  */
steps:
  - name: '${_PRE_REQ_REGION}-docker.pkg.dev/$PROJECT_ID/saas-cloud-build/saas-cloud-build-${_PREFIX}:latest'
    dir: gcp-deployment/single-tenant/terraform/env/saas/regions/cloud-bigquery/scheduled-queries-template/
    entrypoint: 'bash'
    env:
      - "_CUSTOMER_NAME=${_CUSTOMER_NAME}"
      - "_APIGEE=${_APIGEE}"
    args:
    - '-c'
    - |
      git fetch > /dev/null 2>&1
      git checkout  ${_BRANCH_NAME}
      if [ "${_LB_TYPE}" = "http" ] && [ "${_APIGEE}" = "false"  ]; then
        sed -e "s/REGION/$$_CUSTOMER_REGION/g" -e "s/BUILD_PROJECT_ID/$PROJECT_ID/g" -e "s/CUSTOMER_NAME/${_CUSTOMER_NAME}/g" -e "s/BUILD_ID/$BUILD_ID/g" -e "s/FUNCTION_URI/`echo $$_CLOUD_FUNCTION_URI | sed 's#https://##'`/g" script.sh.tpl > script.sh;
        sh script.sh
        rm -rf script.sh
      elif [ "${_LB_TYPE}" = "http" ] && [ "${_APIGEE}" = "true"  ]; then
        sed -e "s/REGION/$$_CUSTOMER_REGION/g" -e "s/BUILD_PROJECT_ID/$PROJECT_ID/g" -e "s/CUSTOMER_NAME/${_CUSTOMER_NAME}/g" -e "s/BUILD_ID/$BUILD_ID/g" -e "s/FUNCTION_URI/`echo $$_CLOUD_FUNCTION_URI | sed 's#https://##'`/g" appigee.sh.tpl > appigee.sh;
        sh appigee.sh
        rm -rf appigee.sh
      else
        sed -e "s/REGION/$$_CUSTOMER_REGION/g" -e "s/BUILD_PROJECT_ID/$PROJECT_ID/g" -e "s/CUSTOMER_NAME/${_CUSTOMER_NAME}/g" -e "s/BUILD_ID/$BUILD_ID/g" -e "s/FUNCTION_URI/`echo $$_CLOUD_FUNCTION_URI | sed 's#https://##'`/g" script-tcp.sh.tpl > script-tcp.sh;
        sh script-tcp.sh
        rm -rf script-tcp.sh
      fi
    secretEnv: ['_CLOUD_FUNCTION_URI','_CUSTOMER_REGION']

  - name: '${_PRE_REQ_REGION}-docker.pkg.dev/$PROJECT_ID/saas-cloud-build/saas-cloud-build-${_PREFIX}:latest'
    id: Remove Directory
    entrypoint: 'bash'
    args:
    - '-eEuo'
    - 'pipefail'
    - '-c'
    - |-
      sed  -e "s/CUSTOMER_NAME/$$_CUSTOMER_NAME/g" gcp-deployment/single-tenant/terraform/env/saas/regions/cloud-bigquery/scheduled-queries-template/setup.py.tpl > gcp-deployment/single-tenant/terraform/env/saas/regions/cloud-bigquery/scheduled-queries-template/setup.py;
      python3 gcp-deployment/single-tenant/terraform/env/saas/regions/cloud-bigquery/scheduled-queries-template/setup.py 
      git add .
      if [ -n "$(git status --porcelain)" ]; then
        echo "There are changes";
        git config --global user.email "$$_CUSTOMER_EMAIL"
        git config --global user.name "$$_CUSTOMER_NAME"
        git commit -m "client $$_CUSTOMER_NAME's scheduled queries deleted"
        git push --set-upstream origin ${_BRANCH_NAME}
      else
        echo "No changes are there";
        exit
      fi
    secretEnv: ['_CUSTOMER_NAME', '_CUSTOMER_EMAIL', 'TF_STATE_BUCKET_NAME', 'LOG_BUCKET_NAME']
    
  - name: '${_PRE_REQ_REGION}-docker.pkg.dev/$PROJECT_ID/saas-cloud-build/saas-cloud-build-${_PREFIX}:latest'
    entrypoint: 'bash'
    env:
      - "_PRE_REQ_REGION=${_PRE_REQ_REGION}"
    args:
    - '-eEuo'
    - 'pipefail'
    - '-c'
    - |-
      git config --global user.email "$$_CUSTOMER_EMAIL"
      git config --global user.name "$$_CUSTOMER_NAME"
      mkdir -p gcp-deployment/single-tenant/terraform/env/saas/regions/cloud-bigquery/$$_CUSTOMER_NAME-scheduled-queries/
      envsubst < gcp-deployment/single-tenant/terraform/env/saas/regions/cloud-bigquery/scheduled-queries-template/terraform.tfvars > gcp-deployment/single-tenant/terraform/env/saas/regions/cloud-bigquery/$$_CUSTOMER_NAME-scheduled-queries/terraform.tfvars
      for f in $(find gcp-deployment/single-tenant/terraform/env/saas/regions/cloud-bigquery/scheduled-queries-template/ -regex '.*\.tf'); do envsubst < $f > "gcp-deployment/single-tenant/terraform/env/saas/regions/cloud-bigquery/$$_CUSTOMER_NAME-scheduled-queries/$(basename $f)"; done
      sed  -e "s/CUSTOMER_NAME/$$_CUSTOMER_NAME/g" -e "s/PREFIX/$$PREFIX/g" -e "s/ENTERPRISE_PROJECT_ID/$$_ENTERPRISE_PROJECT_ID/g" gcp-deployment/single-tenant/terraform/env/saas/regions/cloud-bigquery/scheduled-queries-template/svc_prjct_query01.tpl > gcp-deployment/single-tenant/terraform/env/saas/regions/cloud-bigquery/${_CUSTOMER_NAME}-scheduled-queries/svc_prjct_query01;
      sed  -e "s/CUSTOMER_NAME/$$_CUSTOMER_NAME/g" -e "s/PREFIX/$$PREFIX/g" -e "s/ENTERPRISE_PROJECT_ID/$$_ENTERPRISE_PROJECT_ID/g" gcp-deployment/single-tenant/terraform/env/saas/regions/cloud-bigquery/scheduled-queries-template/svc_prjct_query02.tpl > gcp-deployment/single-tenant/terraform/env/saas/regions/cloud-bigquery/${_CUSTOMER_NAME}-scheduled-queries/svc_prjct_query02;
      sed  -e "s/CUSTOMER_NAME/$$_CUSTOMER_NAME/g" -e "s/PREFIX/$$PREFIX/g" -e "s/ENTERPRISE_PROJECT_ID/$$_ENTERPRISE_PROJECT_ID/g" gcp-deployment/single-tenant/terraform/env/saas/regions/cloud-bigquery/scheduled-queries-template/svc_prjct_query03.tpl > gcp-deployment/single-tenant/terraform/env/saas/regions/cloud-bigquery/${_CUSTOMER_NAME}-scheduled-queries/svc_prjct_query03;
      sed  -e "s/CUSTOMER_NAME/$$_CUSTOMER_NAME/g" -e "s/PREFIX/$$PREFIX/g" -e "s/ENTERPRISE_PROJECT_ID/$$_ENTERPRISE_PROJECT_ID/g" gcp-deployment/single-tenant/terraform/env/saas/regions/cloud-bigquery/scheduled-queries-template/svc_prjct_query04.tpl > gcp-deployment/single-tenant/terraform/env/saas/regions/cloud-bigquery/${_CUSTOMER_NAME}-scheduled-queries/svc_prjct_query04;
      git add .
      git commit -m "client $$_CUSTOMER_NAME's scheduled query created"
      git push --set-upstream origin ${_BRANCH_NAME}
    secretEnv: ['_CUSTOMER_NAME', '_CUSTOMER_EMAIL', 'TF_STATE_BUCKET_NAME', 'LOG_BUCKET_NAME','PREFIX', '_ENTERPRISE_PROJECT_ID','_CUSTOMER_REGION']

  - name: '${_PRE_REQ_REGION}-docker.pkg.dev/$PROJECT_ID/saas-cloud-build/saas-cloud-build-${_PREFIX}:latest' #'hashicorp/terraform:1.0.7'
    args:
      - '-c'
      - |
        cd gcp-deployment/single-tenant/terraform/env/saas/regions/cloud-bigquery/$$_CUSTOMER_NAME-scheduled-queries
        gcloud config set auth/impersonate_service_account ${_CUSTOMER_NAME}-saas-cloudbq-sa@$$_ENTERPRISE_PROJECT_ID.iam.gserviceaccount.com
        export GOOGLE_OAUTH_ACCESS_TOKEN=$(gcloud auth print-access-token)
        terraform init
    id: terraform init
    entrypoint: sh
    secretEnv: ['_CUSTOMER_NAME', '_CUSTOMER_EMAIL', 'TF_STATE_BUCKET_NAME', 'LOG_BUCKET_NAME','_ENTERPRISE_PROJECT_ID']

  - name: '${_PRE_REQ_REGION}-docker.pkg.dev/$PROJECT_ID/saas-cloud-build/saas-cloud-build-${_PREFIX}:latest'
    args:
      - '-c'
      - |
        cd gcp-deployment/single-tenant/terraform/env/saas/regions/cloud-bigquery/$$_CUSTOMER_NAME-scheduled-queries
        terraform fmt
    id: terraform fmt
    entrypoint: sh
    secretEnv: ['_CUSTOMER_NAME', '_CUSTOMER_EMAIL', 'TF_STATE_BUCKET_NAME', 'LOG_BUCKET_NAME']

  - name: '${_PRE_REQ_REGION}-docker.pkg.dev/$PROJECT_ID/saas-cloud-build/saas-cloud-build-${_PREFIX}:latest'
    args:
      - '-c'
      - |
        cd gcp-deployment/single-tenant/terraform/env/saas/regions/cloud-bigquery/$$_CUSTOMER_NAME-scheduled-queries
        terraform validate
    id: terraform validate
    entrypoint: sh
    secretEnv: ['_CUSTOMER_NAME', '_CUSTOMER_EMAIL', 'TF_STATE_BUCKET_NAME', 'LOG_BUCKET_NAME']

  - name: '${_PRE_REQ_REGION}-docker.pkg.dev/$PROJECT_ID/saas-cloud-build/saas-cloud-build-${_PREFIX}:latest'
    args:
      - '-c'
      - |
        cd gcp-deployment/single-tenant/terraform/env/saas/regions/cloud-bigquery/$$_CUSTOMER_NAME-scheduled-queries
        gcloud config set auth/impersonate_service_account ${_CUSTOMER_NAME}-saas-cloudbq-sa@$$_ENTERPRISE_PROJECT_ID.iam.gserviceaccount.com
        export GOOGLE_OAUTH_ACCESS_TOKEN=$(gcloud auth print-access-token)
        terraform plan
    id: terraform plan
    entrypoint: sh
    secretEnv: ['_CUSTOMER_NAME', '_CUSTOMER_EMAIL', 'TF_STATE_BUCKET_NAME', 'LOG_BUCKET_NAME','_ENTERPRISE_PROJECT_ID']

  - name: '${_PRE_REQ_REGION}-docker.pkg.dev/$PROJECT_ID/saas-cloud-build/saas-cloud-build-${_PREFIX}:latest'
    args:
      - '-c'
      - |
        cd gcp-deployment/single-tenant/terraform/env/saas/regions/cloud-bigquery/$$_CUSTOMER_NAME-scheduled-queries
        gcloud config set auth/impersonate_service_account ${_CUSTOMER_NAME}-saas-cloudbq-sa@$$_ENTERPRISE_PROJECT_ID.iam.gserviceaccount.com
        export GOOGLE_OAUTH_ACCESS_TOKEN=$(gcloud auth print-access-token)
        terraform apply -input=false -auto-approve
        gcloud config unset auth/impersonate_service_account
        export GOOGLE_OAUTH_ACCESS_TOKEN=$(gcloud auth print-access-token)
    id: terraform apply
    entrypoint: sh 
    secretEnv: ['_CUSTOMER_NAME', '_CUSTOMER_EMAIL', 'TF_STATE_BUCKET_NAME', 'LOG_BUCKET_NAME','_ENTERPRISE_PROJECT_ID']

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
        gcloud alpha builds triggers run ${_CUSTOMER_NAME}-single-tenant-workload-identity-saas-trigger --branch=${_BRANCH_NAME} --region $$_CUSTOMER_REGION
    id: 'trigger next build'
    secretEnv: ['_CUSTOMER_REGION']

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_NUMBER/secrets/${_CUSTOMER_NAME}-CUSTOMER_NAME/versions/latest
    env: '_CUSTOMER_NAME'
  - versionName: projects/$PROJECT_NUMBER/secrets/${_CUSTOMER_NAME}-CUSTOMER_EMAIL/versions/latest
    env: '_CUSTOMER_EMAIL'
  - versionName: projects/$PROJECT_NUMBER/secrets/${_CUSTOMER_NAME}-TF_STATE_BUCKET_NAME/versions/latest
    env: TF_STATE_BUCKET_NAME
  - versionName: projects/$PROJECT_NUMBER/secrets/${_CUSTOMER_NAME}-LOG_BUCKET_NAME/versions/latest
    env: LOG_BUCKET_NAME
  - versionName: projects/$PROJECT_NUMBER/secrets/${_CUSTOMER_NAME}-PREFIX/versions/latest
    env: PREFIX
  - versionName: projects/$PROJECT_NUMBER/secrets/${_CUSTOMER_NAME}-ENTERPRISE_PROJECT_ID/versions/latest
    env: _ENTERPRISE_PROJECT_ID
  - versionName: projects/$PROJECT_NUMBER/secrets/${_PREFIX}_CLOUD_FUNCTION_URI/versions/latest
    env: _CLOUD_FUNCTION_URI
  - versionName: projects/$PROJECT_NUMBER/secrets/${_CUSTOMER_NAME}-CUSTOMER_REGION/versions/latest
    env: _CUSTOMER_REGION

logsBucket: 'gs://${_LOG_BUCKET_NAME}'
options:
    logging: GCS_ONLY