---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}.nats
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "5"
spec:
  subject:
  secretName: nats-server-tls
  issuerRef:
    name: ipm-ca-issuer
    kind: {{ if .Values.useGoogleCASIssuer }}GoogleCASClusterIssuer{{ else }}ClusterIssuer{{ end }}
    group: {{ if .Values.useGoogleCASIssuer }}cas-issuer.jetstack.io{{ else }}cert-manager.io{{ end }}
  isCA: false
  usages:
    - server auth
    - client auth
  commonName: "{{ .Release.Name }}-nats"
  dnsNames:
  {{- range $i, $val := .Values.global.ingress.tls }}
  {{- range $j, $host := $val.hosts }}
  - {{ $host }}
  {{ end -}}
  {{ end -}}
  - "{{ .Release.Name }}-nats"
  - "{{ .Release.Name }}-nats.{{ .Release.Namespace }}.svc.cluster.local"
  - "nats.{{ .Release.Namespace }}.svc.cluster.local"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}.postgresql
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "5"
spec:
  subject:
  secretName: sql-server-tls
  isCA: false
  usages:
    - server auth
    - client auth
  issuerRef:
    name: ipm-ca-issuer
    kind: {{ if .Values.useGoogleCASIssuer }}GoogleCASClusterIssuer{{ else }}ClusterIssuer{{ end }}
    group: {{ if .Values.useGoogleCASIssuer }}cas-issuer.jetstack.io{{ else }}cert-manager.io{{ end }}
  commonName: "{{ .Release.Name }}-postgresql"
  dnsNames:
  {{- range $i, $val := .Values.global.ingress.tls }}
  {{- range $j, $host := $val.hosts }}
  - {{ $host }}
  {{ end -}}
  {{ end -}}
  - "{{ .Release.Name }}-postgresql"
  - "{{ .Release.Name }}-postgresql-hl"
  - "{{ .Release.Name }}-postgresql.{{ .Release.Namespace }}.svc.cluster.local"
  - "{{ .Release.Name }}-postgresql-hl.{{ .Release.Namespace }}.svc.cluster.local"
  - "postgresql.{{ .Release.Namespace }}.svc.cluster.local"
  - "postgresql-hl.{{ .Release.Namespace }}.svc.cluster.local"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}.mongodb
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "5"
spec:
  subject:
  secretName: mongodb-server-tls
  isCA: false
  usages:
    - server auth
    - client auth
  issuerRef:
    name: ipm-ca-issuer
    kind: {{ if .Values.useGoogleCASIssuer }}GoogleCASClusterIssuer{{ else }}ClusterIssuer{{ end }}
    group: {{ if .Values.useGoogleCASIssuer }}cas-issuer.jetstack.io{{ else }}cert-manager.io{{ end }}
  commonName: "{{ .Release.Name }}-mongodb"
  ipAddresses:
  - 127.0.0.1
  dnsNames:
  {{- range $i, $val := .Values.global.ingress.tls }}
  {{- range $j, $host := $val.hosts }}
  - {{ $host }}
  {{ end }}
  {{ end }}
  - "{{ .Release.Name }}-mongodb"
  - "{{ .Release.Name }}-mongodb-headless"
  - "{{ .Release.Name }}-mongodb-0.{{ .Release.Name }}-mongodb-headless"
  - "{{ .Release.Name }}-mongodb.{{ .Release.Namespace }}.svc.cluster.local"
  - "{{ .Release.Name }}-mongodb-headless.{{ .Release.Namespace }}.svc.cluster.local"
  - "mongodb-0.mongodb-headless.{{ .Release.Namespace }}.svc.cluster.local"
  - "mongodb-headless.{{ .Release.Namespace }}.svc.cluster.local"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}.emqx
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "5"
spec:
  subject:
  secretName: mqtt-server-tls
  isCA: false
  usages:
    - server auth
    - client auth
  issuerRef:
    name: ipm-ca-issuer
    kind: {{ if .Values.useGoogleCASIssuer }}GoogleCASClusterIssuer{{ else }}ClusterIssuer{{ end }}
    group: {{ if .Values.useGoogleCASIssuer }}cas-issuer.jetstack.io{{ else }}cert-manager.io{{ end }}
  commonName: "{{ .Release.Name }}-emqx"
  dnsNames:
  {{- range $i, $val := .Values.global.ingress.tls }}
  {{- range $j, $host := $val.hosts }}
  - {{ $host }}
  {{ end }}
  {{ end }}
  - "{{ .Release.Name }}-emqx"
  - "{{ .Release.Name }}-emqx-headless"
  - "{{ .Release.Name }}-emqx.{{ .Release.Namespace }}.svc.cluster.local"
  - "{{ .Release.Name }}-emqx-headless.{{ .Release.Namespace }}.svc.cluster.local"
  - "emqx.{{ .Release.Namespace }}.svc.cluster.local"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}.postgresql-client
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "10"
spec:
  subject:
  secretName: sql-client-tls
  isCA: false
  usages:
    - server auth
    - client auth
  additionalOutputFormats:
  - type: CombinedPEM
  - type: DER
  issuerRef:
    name: ipm-ca-issuer
    kind: {{ if .Values.useGoogleCASIssuer }}GoogleCASClusterIssuer{{ else }}ClusterIssuer{{ end }}
    group: {{ if .Values.useGoogleCASIssuer }}cas-issuer.jetstack.io{{ else }}cert-manager.io{{ end }}
  commonName: "dbusername"
  dnsNames:
  - "{{ .Release.Name }}-postgresql"
  - "{{ .Release.Name }}-postgresql-hl"
  - "{{ .Release.Name }}-postgresql.{{ .Release.Namespace }}.svc.cluster.local"
  - "postgresql.{{ .Release.Namespace }}.svc.cluster.local"
  - "{{ .Release.Name }}-postgresql-hl.{{ .Release.Namespace }}.svc.cluster.local"