apiVersion: v1
kind: Secret
metadata:
  name: ipm-postgresql-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "5"
type: Opaque
data:
  postgres_password: {{ .Values.global.postgres.postgres_password }}
  password: {{ .Values.global.postgres.password }}
  replication_password: {{ .Values.global.postgres.replication_password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: pgpass
data:
  pgpass: aW5mLXBvc3RncmVzcWw6NTQzMjoqOnBvc3RncmVzOmluZmluZXJhMQo=
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: backup-mongodb-client-tls
spec:
  subject:
  secretName: backup-mongodb-client-tls
  isCA: false
  usages:
    - server auth
    - client auth
  additionalOutputFormats:
  - type: CombinedPEM
  issuerRef:
    name: ipm-ca-issuer
    kind: {{ if .Values.useGoogleCASIssuer }}GoogleCASClusterIssuer{{ else }}ClusterIssuer{{ end }}
    group: {{ if .Values.useGoogleCASIssuer }}cas-issuer.jetstack.io{{ else }}cert-manager.io{{ end }}
  commonName: "backup-mongodb"
  ipAddresses:
  - 127.0.0.1
  dnsNames:
  - "mongodb-0.mongodb-headless.{{ .Release.Namespace }}.svc.cluster.local"
  - "mongodb-headless.{{ .Release.Namespace }}.svc.cluster.local"