---
kind: ConfigMap
apiVersion: v1
metadata:
  name: network-inventory
  labels:
    grafana_dashboard: "1"
data:
  network_inventory.json: |-
    {{- $.Files.Get "dashboards/Network_Inventory.json"  | nindent 4 -}}