---
kind: ConfigMap
apiVersion: v1
metadata:
  name: test-turnup-panel
  labels:
    grafana_dashboard: "1"
data:
  testturnup_panel.json: |-
    {{- $.Files.Get "dashboards/test_trunup_panel.json"  | nindent 4 -}}