{{- if not (lookup "cert-manager.io/v1" "Certificate" .Release.Namespace "inf.postgresql-client") }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}.postgresql-client
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "10"
spec:
  subject:
  secretName: sql-client-tls
  isCA: false
  usages:
    - server auth
    - client auth
  additionalOutputFormats:
  - type: CombinedPEM
  - type: DER
  issuerRef:
    name: ipm-ca-issuer
    kind: {{ if .Values.useGoogleCASIssuer }}GoogleCASClusterIssuer{{ else }}ClusterIssuer{{ end }}
    group: {{ if .Values.useGoogleCASIssuer }}cas-issuer.jetstack.io{{ else }}cert-manager.io{{ end }}
  commonName: "dbusername"
  dnsNames:
  - "{{ .Release.Name }}-postgresql"
  - "{{ .Release.Name }}-postgresql-hl"
  - "{{ .Release.Name }}-postgresql.{{ .Release.Namespace }}.svc.cluster.local"
  - "postgresql.{{ .Release.Namespace }}.svc.cluster.local"
  - "{{ .Release.Name }}-postgresql-hl.{{ .Release.Namespace }}.svc.cluster.local"
  {{- end }} 