apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "DomainManager.web-gui.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "DomainManager.labels" . | nindent 4 }}
    {{- with .Values.web.deploymentLabels }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
  {{- with .Values.web.deploymentAnnotations }}
  annotations:
  {{- . | toYaml | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
       {{- include "DomainManager.web-gui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.web.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "DomainManager.web-gui.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.web.securityContext }}
      securityContext:
              {{- toYaml . | nindent 8 }}
            {{- end }}
            {{- if .Values.web.rbac.enabled }}
      serviceAccountName: {{ .Values.web.rbac.serviceAccountName }}
            {{- end }}
            {{- with .Values.web.image.imagePullSecrets }}
      imagePullSecrets:
              {{- toYaml . | nindent 8 }}
            {{- end }}
      restartPolicy: {{ .Values.web.restartPolicy }}
            {{- if .Values.web.initContainersTpl }}
      initContainers:
            {{- tpl .Values.web.initContainersTpl . | nindent 8 }}
            {{- end }}

      containers:
        - name: {{ .Values.web.name }}
          image: {{ include "DomainManager.web-gui.image" . | quote }}
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            - name: web-gui-port
              containerPort: {{ .Values.web.port | default "8080"}}
              protocol: TCP
          {{- with .Values.web.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ .Values.web.name  }}-configmap
      restartPolicy: {{ .Values.web.restartPolicy }}

      volumes:
        - name: {{ .Values.web.config.volume }}
          configMap:
             name: {{ include "DomainManager.web-gui.configName" . }}
        {{- with .Values.web.extraVolumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
status: {}
