installCRDs: true
featureGates: "AdditionalCertificateOutputFormats=true,UseCertificateRequestBasicConstraints=true"
webhook:
  extraArgs:
    - "--feature-gates=AdditionalCertificateOutputFormats=true"