apiVersion: v1
kind: Service
metadata:
  name: {{ include "DomainManager.module-manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
      {{- include "DomainManager.labels" . | nindent 4 }}
      {{- with .Values.mm.service.labels }}
      {{- . | toYaml | nindent 4 }}
      {{- end }}
spec:
  type: {{ .Values.mm.service.type | default "ClusterIP" }}
  ports:
  - name: mm-port
    port: {{ .Values.mm.port | default "8080" }}
    targetPort: mm-port
  selector:
   {{- include "DomainManager.module-manager.selectorLabels" . | nindent 4 }}