apiVersion: v2
name: infrastructure
description: A Helm chart for IPM Infrastructure
type: application
version: v1.2.4
appVersion: v1.2.4
dependencies:
- name: nats
  repository: https://nats-io.github.io/k8s/helm/charts/
  version: 0.19.5
  condition: nats.enabled
- name: mongodb
  repository: https://charts.bitnami.com/bitnami
  version: 13.13.0
  condition: mongodb.enabled
- name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 12.1.9
  condition: postgresql.enabled
- name: emqx
  repository: https://repos.emqx.io/charts
  version: 5.0.25
  condition: eqmx.enabled
