# /*
#  * Copyright 2022 Google LLC. 
#  * 
#  * This software is provided as-is, without warranty or representation for any use or purpose. 
#  * Your use of it is subject to your agreement with Google.
#  */
steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Generate manifest for deployment
    dir: gcp-deployment/terraform/env/saas/regions/apigee
    secretEnv: ['ADMIN_DOMAIN' , 'HOST_PROJECT_ID']
    entrypoint: /bin/sh
    args:
      - '-c'
      - | 
        sed -e "s/TF_BUCKET_NAME/${_TFSTATE_GCS_BUCKET_NAME}/g" -e "s/PREFIX_NAME/${_PREFIX}/g" -e "s/REGION_NAME/${_REGION}/g" -e "s/FULL_ADMIN_DOMAIN/$$ADMIN_DOMAIN/g" -e "s/HOST_PROJECT_ID/$$HOST_PROJECT_ID/g" terraform.tfvars.tpl > terraform.tfvars;        
        sed -e "s/TF_BUCKET_NAME/${_TFSTATE_GCS_BUCKET_NAME}/g" -e "s/PREFIX_NAME/${_PREFIX}/g" backend.tf.tpl > backend.tf;
        sed -e "s/PREFIX_NAME/${_PREFIX}/g" -e "s/FULL_ADMIN_DOMAIN/$$ADMIN_DOMAIN/g" main.tf.tpl > main.tf;
        sed -e "s/PREFIX_NAME/${_PREFIX}/g" outputs.tf.tpl > outputs.tf

  - name: '${_REGION}-docker.pkg.dev/$PROJECT_ID/saas-cloud-build/saas-cloud-build-${_PREFIX}:latest'
    dir: gcp-deployment/terraform/env/saas/regions/apigee
    args:
      - '-c'
      - |
        terraform init
    id: terraform init
    entrypoint: sh
  - name: '${_REGION}-docker.pkg.dev/$PROJECT_ID/saas-cloud-build/saas-cloud-build-${_PREFIX}:latest'
    dir: gcp-deployment/terraform/env/saas/regions/apigee
    args:
      - '-c'
      - |
        terraform fmt
    id: terraform fmt
    entrypoint: sh
  - name: '${_REGION}-docker.pkg.dev/$PROJECT_ID/saas-cloud-build/saas-cloud-build-${_PREFIX}:latest'
    dir: gcp-deployment/terraform/env/saas/regions/apigee
    args:
      - '-c'
      - |
        terraform validate
    id: terraform validate
    entrypoint: sh
  - name: '${_REGION}-docker.pkg.dev/$PROJECT_ID/saas-cloud-build/saas-cloud-build-${_PREFIX}:latest'
    dir: gcp-deployment/terraform/env/saas/regions/apigee
    args:
      - '-c'
      - |
        terraform plan
    id: terraform plan
    entrypoint: sh

  - name: '${_REGION}-docker.pkg.dev/$PROJECT_ID/saas-cloud-build/saas-cloud-build-${_PREFIX}:latest'
    dir: gcp-deployment/terraform/env/saas/regions/apigee
    args:
      - '-c'
      - |
        terraform apply -input=false -auto-approve
    id: terraform apply
    entrypoint: sh

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['alpha', 'builds', 'triggers', 'run', 'apigee-components-${_PREFIX}-trigger', '--branch=${_BRANCH_NAME}']
    id: 'trigger next build'
  
logsBucket: 'gs://${_LOGS_GCS_BUCKET_NAME}'
options:
  logging: GCS_ONLY
timeout: 86400s
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_NUMBER/secrets/${_PREFIX}_HOST_PROJECT_ID/versions/latest
    env: HOST_PROJECT_ID
  - versionName: projects/$PROJECT_NUMBER/secrets/${_PREFIX}_ADMIN_DOMAIN/versions/latest
    env: 'ADMIN_DOMAIN'
