apiVersion: v1
kind: Service
metadata:
  name: {{ include "DomainManager.host-management-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
      {{- include "DomainManager.labels" . | nindent 4 }}
      {{- with .Values.hms.service.labels }}
      {{- . | toYaml | nindent 4 }}
      {{- end }}
spec:
  type: {{ .Values.hms.service.type | default "ClusterIP" }}
  ports:
  - name: hms-port
    port: {{ .Values.hms.port | default "8080" }}
    targetPort: hms-port
  selector:
   {{- include "DomainManager.host-management-service.selectorLabels" . | nindent 4 }}