apiVersion: v1
kind: Service
metadata:
  name: {{ include "DomainManager.event-gateway.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
      {{- include "DomainManager.labels" . | nindent 4 }}
      {{- with .Values.eg.service.labels }}
      {{- . | toYaml | nindent 4 }}
      {{- end }}
spec:
  type: {{ .Values.eg.service.type | default "ClusterIP" }}
  ports:
  - name: eg-port
    port: {{ .Values.eg.port | default "8080" }}
    targetPort: eg-port
  selector:
   {{- include "DomainManager.event-gateway.selectorLabels" . | nindent 4 }}