{{- if .Values.ums.ingress.enabled -}}
{{- $fullName := include "DomainManager.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}.{{ .Values.ums.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "DomainManager.labels" . | nindent 4 }}
  {{- with .Values.ums.ingress.annotations }}
  annotations:
    {{- include "DomainManager.common-ingress.annotations" . | nindent 4 }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.global.ingress.ingressClassName }}
  rules:
    {{- range $host := .Values.global.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          {{- range $.Values.ums.ingress.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ .backend.service.name }}
                port:
                  number: 8080
          {{- end }}
    {{- end }}
{{- end }}
