apiVersion: v1
kind: Service
metadata:
  name: {{ include "DomainManager.user-manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
      {{- include "DomainManager.labels" . | nindent 4 }}
      {{- with .Values.ums.service.labels }}
      {{- . | toYaml | nindent 4 }}
      {{- end }}
spec:
  type: {{ .Values.ums.service.type | default "ClusterIP" }}
  ports:
    - name: ums-port
      port: {{ .Values.ums.port | default "8080" }}
      targetPort: ums-port
  selector:
   {{- include "DomainManager.user-manager.selectorLabels" . | nindent 4 }}
