apiVersion: v1
kind: Service
metadata:
  name: {{ include "DomainManager.software-manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
      {{- include "DomainManager.labels" . | nindent 4 }}
      {{- with .Values.swm.service.labels }}
      {{- . | toYaml | nindent 4 }}
      {{- end }}
spec:
  type: {{ .Values.swm.service.type | default "ClusterIP" }}
  ports:
    - name: swm-port
      port: {{ .Values.swm.port | default "8080" }}
      targetPort: swm-port
  selector:
   {{- include "DomainManager.software-manager.selectorLabels" . | nindent 4 }}