# /*
#  * Copyright 2022 Google LLC. 
#  * 
#  * This software is provided as-is, without warranty or representation for any use or purpose. 
#  * Your use of it is subject to your agreement with Google.
#  */
steps:
    - name: 'gcr.io/cloud-builders/gcloud'
      id: Generate manifest for deployment
      dir: gcp-deployment/terraform/env/saas/global/cloud-dns/public-dns
      secretEnv: ['FREEMIUM_SUB_DOMAIN', 'ENTERPRISE_SUB_DOMAIN', 'ADMIN_DOMAIN']
      entrypoint: sh
      args:
      - '-c'
      - | 
        sed -e "s/FULL_ADMIN_DOMAIN/$$ADMIN_DOMAIN/g" -e "s/FULL_FREEMIUM_SUB_DOMAIN/$$FREEMIUM_SUB_DOMAIN/g" -e "s/FULL_ENTERPRISE_SUB_DOMAIN/$$ENTERPRISE_SUB_DOMAIN/g" -e "s/REGION_NAME/${_REGION}/g" -e "s/ZONE_NAME/${_ZONE}/g" -e "s/TF_BUCKET_NAME/${_TFSTATE_GCS_BUCKET_NAME}/g" -e "s/LOGS_BUCKET_NAME/${_LOGS_GCS_BUCKET_NAME}/g" -e "s/CUSTOMER_DOMAIN/${_SUB_DOMAIN}/g" -e "s/PREFIX_NAME/${_PREFIX}/g"  -e "s/CODE_REPOSITORY_NAME/${_REPO_NAME}/g" -e "s/TEMP_SEED_PROJECT_ID/${_TEMP_SEED_PROJECT_ID}/g" -e "s/REPO_BRANCH_NAME/${_BRANCH_NAME}/g"  terraform.tfvars.tpl > terraform.tfvars;
        sed -e "s/TF_BUCKET_NAME/${_TFSTATE_GCS_BUCKET_NAME}/g" -e "s/PREFIX_NAME/${_PREFIX}/g" backend.tf.tpl > backend.tf
        sed -e "s/FULL_ADMIN_DOMAIN/$$ADMIN_DOMAIN/g" -e "s/CUSTOMER_DOMAIN/${_SUB_DOMAIN}/g" -e "s/PREFIX_NAME/${_PREFIX}/g"  main.tf.tpl > main.tf;
        ls -lart
        cat terraform.tfvars
    - name: '${_REGION}-docker.pkg.dev/$PROJECT_ID/saas-cloud-build/saas-cloud-build-${_PREFIX}:latest'
      dir: gcp-deployment/terraform/env/saas/global/cloud-dns/public-dns
      args:
        - '-c'
        - |
          terraform init
      id: terraform init
      entrypoint: sh
    - name: '${_REGION}-docker.pkg.dev/$PROJECT_ID/saas-cloud-build/saas-cloud-build-${_PREFIX}:latest'
      dir: gcp-deployment/terraform/env/saas/global/cloud-dns/public-dns
      args:
        - '-c'
        - |
          terraform fmt
      id: terraform fmt
      entrypoint: sh
    - name: '${_REGION}-docker.pkg.dev/$PROJECT_ID/saas-cloud-build/saas-cloud-build-${_PREFIX}:latest'
      dir: gcp-deployment/terraform/env/saas/global/cloud-dns/public-dns
      args:
        - '-c'
        - |
          terraform validate
      id: terraform validate
      entrypoint: sh
    - name: '${_REGION}-docker.pkg.dev/$PROJECT_ID/saas-cloud-build/saas-cloud-build-${_PREFIX}:latest'
      dir: gcp-deployment/terraform/env/saas/global/cloud-dns/public-dns
      args:
        - '-c'
        - |
          terraform plan
      id: terraform plan
      entrypoint: sh
    - name: '${_REGION}-docker.pkg.dev/$PROJECT_ID/saas-cloud-build/saas-cloud-build-${_PREFIX}:latest'
      dir: gcp-deployment/terraform/env/saas/global/cloud-dns/public-dns
      args:
        - '-c'
        - |
          terraform apply -input=false -auto-approve
      id: terraform apply
      entrypoint: sh 

logsBucket: 'gs://${_LOGS_GCS_BUCKET_NAME}'
options:
    logging: GCS_ONLY
timeout: 86400s
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_NUMBER/secrets/${_PREFIX}_FREEMIUM_SUB_DOMAIN/versions/latest
    env: 'FREEMIUM_SUB_DOMAIN'
  - versionName: projects/$PROJECT_NUMBER/secrets/${_PREFIX}_ENTERPRISE_SUB_DOMAIN/versions/latest
    env: 'ENTERPRISE_SUB_DOMAIN'
  - versionName: projects/$PROJECT_NUMBER/secrets/${_PREFIX}_ADMIN_DOMAIN/versions/latest
    env: 'ADMIN_DOMAIN'