apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aggregation-manager.device-configuration-distributor.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aggregation-manager.labels" . | nindent 4 }}
    {{- with .Values.dcd.deploymentLabels }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
  {{- with .Values.dcd.deploymentAnnotations }}
  annotations:
  {{- . | toYaml | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.dcd.replicas }}
  selector:
    matchLabels:
       {{- include "aggregation-manager.device-configuration-distributor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.dcd.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "aggregation-manager.device-configuration-distributor.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.dcd.securityContext }}
      securityContext:
              {{- toYaml . | nindent 8 }}
            {{- end }}
            {{- if .Values.dcd.rbac.enabled }}
      serviceAccountName: {{ .Values.dcd.rbac.serviceAccountName }}
            {{- end }}
            {{- with .Values.dcd.image.imagePullSecrets }}
      imagePullSecrets:
              {{- toYaml . | nindent 8 }}
            {{- end }}
      restartPolicy: {{ .Values.dcd.restartPolicy }}
      initContainers:
        - name: check-mongodb-service
          image: {{  .Values.global.images.initContainers.busybox  | default  ( include "aggregation-manager.busybox.image" .) | quote}}
          command: ['sh', '-c', 'until nslookup $(SERVER_ADDR); do echo waiting for mongodb service; sleep 5; done;']
          env:
            - name: SERVER_ADDR
              value: {{ printf " " }}{{  .Values.dcd.clients.mongoDB.uri  | default  ( include "aggregation-manager.mongoDBSrvAddr" .) | quote}}
        - name: check-nats-service
          image: {{  .Values.global.images.initContainers.busybox  | default  ( include "aggregation-manager.busybox.image" .) | quote}}
          command: ['sh', '-c', 'until nslookup $(SERVER_ADDR); do echo waiting for nats service; sleep 5; done;']
          env:
            - name: SERVER_ADDR
              value: {{ printf " " }}{{  .Values.dcd.clients.jetstream.uri  | default  ( include "aggregation-manager.jetstreamSrvAddr" .) | quote}}          
        - name: check-jetstream-stream-aggregation-manager
          image: {{  .Values.global.images.initContainers.natsbox  | default  ( include "aggregation-manager.nats-box.image" .) | quote}}
          command: ['sh', '-c', 'until  [[ "$(SERVER_ADDR)" =~ "EVENTS" ]]; do echo waiting for nats stream EVENTS to be created $(SERVER_ADDR); sleep 5; done;']
          env:
            - name: SERVER_ADDR
              value: {{ printf " $(nats -s " }}{{  .Values.dcd.clients.jetstream.uri  | default  ( include "aggregation-manager.jetstreamSrvAddr" .) | quote}}{{printf " --tlscert=/certs/jetstream/tls.crt --tlskey=/certs/jetstream/tls.key --tlsca=/certs/jetstream/ca.crt stream ls -n)"}}
          volumeMounts:
            {{- with .Values.dcd.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}         
        - name: check-mqtt-service
          image: {{  .Values.global.images.initContainers.busybox  | default  ( include "aggregation-manager.busybox.image" .) | quote}}
          command: ['sh', '-c', 'until nslookup $(SERVER_ADDR); do echo waiting for mqtt service; sleep 5; done;']
          env:
            - name: SERVER_ADDR
              value: {{ printf " " }}{{  .Values.dcd.clients.mqtt.uri  | default  ( include "aggregation-manager.mqttSrvAddr" .) | quote}}
      containers:
        - name: {{ .Values.dcd.name }}
          image: {{ include "aggregation-manager.device-configuration-distributor.image" . | quote }}
          imagePullPolicy: {{ .Values.dcd.image.pullPolicy }}
          ports:
            - name: dcd-port
              containerPort: {{ .Values.dcd.port | default "8080"}}
              protocol: TCP
          {{- with .Values.dcd.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ .Values.dcd.name  }}-configmap
          volumeMounts:
            {{- with .Values.dcd.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}    
            {{- with .Values.global.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}    
      restartPolicy: {{ .Values.dcd.restartPolicy }}

      volumes:
        - name: {{ .Values.dcd.config.volume }}
          configMap:
             name: {{ include "aggregation-manager.device-configuration-distributor.configName" . }}
        {{- with .Values.dcd.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.global.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
status: {}
