{
 "title": "Historical PMs with aggregation - per device",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "sn",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(bucket: \"xr-1m\", tag: \"sn\")"
   },
   {
    "name": "di",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(bucket: \"xr-1m\", tag: \"di\")"
   },
   {
    "name": "aids",
    "query": " 1, 2, 3, 4, 5, 6, 7,8,9,10,11,12,13,14,15,16"
   },
   { "name": "records", "query": "1, 5, 10, 15, 20, 25" },
   { "name": "interval", "query": "1m,15m,1h,24h,30d" },
   {
    "name": "metrics",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.measurements(bucket: \"xr-1m\")"
   },
   {
    "name": "attributes",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagKeys(bucket: \"xr-1m\")"
   },
   {
    "name": "metrics_2",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.measurements(bucket: \"xr-1m\")"
   }
  ]
 },
 "panels": [
  { "title": "Module, Carrier PMs ${di}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "di" },
  {
   "title": "Module PMs",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"xr-1m\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\")\r\n  |> filter(fn: (r) => r[\"rt\"] == \"lineptp\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] !~ /_min/ and r[\"_measurement\"] !~ /_max/ and r[\"_measurement\"] !~ /_avg/)\r\n  |> filter(fn: (r) => r[\"sn\"] =~ /^${sn:regex}/)\r\n  |> filter(fn: (r) => r[\"di\"] =~ /^${di:regex}/)\r\n  |> sort(columns: [\"_time\"], desc: true)\r\n  |> aggregateWindow(every: ${interval}, fn: mean)\r\n  |> limit (n:${records})\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_measurement\"], valueColumn: \"_value\")\r\n "
    }
   ]
  },
  {
   "title": "Carrier PMs",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"xr-1m\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\")\r\n  |> filter(fn: (r) => r[\"rt\"] == \"carrier\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] !~ /_min/ and r[\"_measurement\"] !~ /_max/ and r[\"_measurement\"] !~ /_avg/)\r\n  |> filter(fn: (r) => r[\"sn\"] =~ /^${sn:regex}/)\r\n  |> filter(fn: (r) => r[\"di\"] =~ /^${di:regex}/)\r\n  |> sort(columns: [\"_time\"], desc: true)\r\n  |> aggregateWindow(every: ${interval}, fn: mean)\r\n  |> limit (n:${records})\r\n  |> pivot(rowKey: [\"_time\", \"aid\"], columnKey: [\"_measurement\"], valueColumn: \"_value\")\r\n \r\n\r\n"
    }
   ]
  },
  {
   "title": "DSC PMs",
   "type": "table",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"xr-1m\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\")\r\n  |> filter(fn: (r) => r[\"rt\"] == \"dsc\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] !~ /_min/ and r[\"_measurement\"] !~ /_max/ and r[\"_measurement\"] !~ /_avg/)\r\n  |> filter(fn: (r) => r[\"sn\"] =~ /^${sn:regex}/)\r\n  |> filter(fn: (r) => r[\"di\"] =~ /^${di:regex}/)\r\n  |> filter(fn: (r) => r[\"aid\"] =~ /^${aids:regex}$/)\r\n  |> sort(columns: [\"_time\"], desc: true)\r\n  |> aggregateWindow(every: ${interval}, fn: mean)\r\n  |> limit (n:${records})\r\n  |> pivot(rowKey: [\"_time\", \"aid\"], columnKey: [\"_measurement\"], valueColumn: \"_value\")\r\n  |> map(      \r\n    fn: (r) => ({r with\r\n        \"DSC State\": if r._value == 0 then \"not configured\"\r\n        else if r._value == .25 then \"powered down\"\r\n        else if r._value == 0.144742 then \"not acquired\"\r\n        else \"ok\"\r\n\r\n    }))\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "OTU PMs",
   "type": "table",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"xr-1m\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\" or r[\"_field\"] == \"counter\")\r\n  |> filter(fn: (r) => r[\"rt\"] == \"otu\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] !~ /_min/ and r[\"_measurement\"] !~ /_max/ and r[\"_measurement\"] !~ /_avg/)\r\n  |> filter(fn: (r) => r[\"sn\"] =~ /^${sn:regex}/)\r\n  |> filter(fn: (r) => r[\"di\"] =~ /^${di:regex}/)\r\n  |> sort(columns: [\"_time\"], desc: true)\r\n  |> aggregateWindow(every: ${interval}, fn: mean)\r\n  |> limit (n:${records})\r\n  |> pivot(rowKey: [\"_time\", \"aid\"], columnKey: [\"_measurement\"], valueColumn: \"_value\")\r\n\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "ODU PMs",
   "type": "table",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"xr-1m\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\" or r[\"_field\"] == \"counter\")\r\n  |> filter(fn: (r) => r[\"rt\"] == \"odu\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] !~ /_min/ and r[\"_measurement\"] !~ /_max/ and r[\"_measurement\"] !~ /_avg/)\r\n  |> filter(fn: (r) => r[\"sn\"] =~ /^${sn:regex}/)\r\n  |> filter(fn: (r) => r[\"di\"] =~ /^${di:regex}/)\r\n  |> sort(columns: [\"_time\"], desc: true)\r\n  |> aggregateWindow(every: ${interval}, fn: mean)\r\n  |> limit (n:${records})\r\n  |> pivot(rowKey: [\"_time\", \"aid\"], columnKey: [\"_measurement\"], valueColumn: \"_value\")\r\n\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "GigE Client PMs",
   "type": "table",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"xr-1m\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\" or r[\"_field\"] == \"counter\")\r\n  |> filter(fn: (r) => r[\"rt\"] == \"clientptp\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] !~ /_min/ and r[\"_measurement\"] !~ /_max/ and r[\"_measurement\"] !~ /_avg/)\r\n  |> filter(fn: (r) => r[\"sn\"] =~ /^${sn:regex}/)\r\n  |> filter(fn: (r) => r[\"di\"] =~ /^${di:regex}/)\r\n  |> sort(columns: [\"_time\"], desc: true)\r\n  |> aggregateWindow(every: ${interval}, fn: mean)\r\n  |> limit (n:${records})\r\n  |> pivot(rowKey: [\"_time\", \"aid\"], columnKey: [\"_measurement\"], valueColumn: \"_value\")\r\n\r\n\r\n\r\n"
    }
   ]
  }
 ]
}