{
 "title": "Metrics-Explore - Per Resource",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "di",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(bucket: \"xr-1m\", tag: \"di\")"
   },
   {
    "name": "rt",
    "query": "lineptp,dsc,carrier,otu,odu,client"
   },
   {
    "name": "line_m",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.measurements(bucket: \"xr-1m\")\r\n|> filter(fn: (r) => r[\"_value\"] =~ /lineptp/)\r\n"
   },
   {
    "name": "client_m",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.measurements(bucket: \"xr-1m\")\r\n|> filter(fn: (r) => r[\"_value\"] =~ /client/)\r\n"
   },
   {
    "name": "dsc_m",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.measurements(bucket: \"xr-1m\")\r\n|> filter(fn: (r) => r[\"_value\"] =~ /dsc/)\r\n"
   },
   {
    "name": "carrier_m",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.measurements(bucket: \"xr-1m\")\r\n|> filter(fn: (r) => r[\"_value\"] =~ /carrier/)\r\n"
   },
   {
    "name": "odu_m",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.measurements(bucket: \"xr-1m\")\r\n|> filter(fn: (r) => r[\"_value\"] =~ /odu/)\r\n"
   },
   {
    "name": "otu_m",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.measurements(bucket: \"xr-1m\")\r\n|> filter(fn: (r) => r[\"_value\"] =~ /otu/)\r\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Total # of Metrics",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\r\nschema.measurements(bucket: \"xr-1m\")\r\n|>count()"
    }
   ]
  },
  {
   "title": "# of devices",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(bucket: \"xr-1m\", tag: \"sn\")\r\n|>count()"
    }
   ]
  },
  { "title": "Filter Panel", "type": "alertlist", "gridPos": { "h": 3, "w": 5, "x": 4, "y": 0 } },
  { "title": "Status $di", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }, "repeat": "di" },
  {
   "title": "linepm count $di",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\r\nfrom(bucket: \"xr-1m\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\" or r[\"_field\"] == \"counter\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /case/)\r\n    |> filter(fn: (r) => r[\"di\"] =~ /^${di:regex}/)\r\n    |> aggregateWindow(every: 1m, fn: last, createEmpty: false)\r\n    \r\n    |> count()"
    }
   ]
  },
  {
   "title": "dsc count $di",
   "type": "stat",
   "gridPos": { "h": 6, "w": 11, "x": 2, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\r\nfrom(bucket: \"xr-1m\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\" or r[\"_field\"] == \"counter\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"xr.dsc.1m.osnr_rx_ne_min\")\r\n    |> filter(fn: (r) => r[\"di\"] =~ /^${di:regex}/)\r\n    |> aggregateWindow(every: 1m, fn: last, createEmpty: false)\r\n    \r\n    |> count()"
    }
   ]
  },
  {
   "title": "client count $di",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 13, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\r\nfrom(bucket: \"xr-1m\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\" or r[\"_field\"] == \"counter\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"xr.clientptp.packets_rx_ne\")\r\n    |> filter(fn: (r) => r[\"di\"] =~ /^${di:regex}/)\r\n    |> aggregateWindow(every: 1m, fn: last, createEmpty: false)\r\n    \r\n    |> count()"
    }
   ]
  },
  {
   "title": "carrier count $di",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 15, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\r\nfrom(bucket: \"xr-1m\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\" or r[\"_field\"] == \"counter\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"xr.carrier.1m.lbc_tx_ne_min\")\r\n    |> filter(fn: (r) => r[\"di\"] =~ /^${di:regex}/)\r\n    |> aggregateWindow(every: 1m, fn: last, createEmpty: false)\r\n    \r\n    |> count()"
    }
   ]
  },
  {
   "title": "OTU count $di",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 17, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\r\nfrom(bucket: \"xr-1m\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\" or r[\"_field\"] == \"counter\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"xr.otu.odu.errored_blocks_rx_ne\")\r\n    |> filter(fn: (r) => r[\"di\"] =~ /^${di:regex}/)\r\n    |> aggregateWindow(every: 1m, fn: last, createEmpty: false)\r\n    \r\n    |> count()"
    }
   ]
  },
  {
   "title": "ODU count $di",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 19, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\r\nfrom(bucket: \"xr-1m\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\" or r[\"_field\"] == \"counter\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"xr.otu.odu.errored_seconds_rx_ne\")\r\n    |> filter(fn: (r) => r[\"di\"] =~ /^${di:regex}/)\r\n    |> aggregateWindow(every: 1m, fn: last, createEmpty: false)\r\n    \r\n    |> count()"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 10 },
   "repeat": "di",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"xr-1m\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\" or r[\"_field\"] == \"counter\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /temp/)\r\n    |> filter(fn: (r) => r[\"di\"] =~ /^${di:regex}/)\r\n\r\n      |> pivot(rowKey: [\"_time\"], columnKey: [\"_measurement\"], valueColumn: \"_value\")\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Line PM - $di",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Line PM:$line_m",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 2.1818181818181817, "x": 0, "y": 15 },
     "repeat": "line_m",
     "targets": [
      {
       "query": "from(bucket: \"xr-1m\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\" or r[\"_field\"] == \"counter\"  )\r\n  |> filter(fn: (r) => r[\"di\"] == \"${di}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${line_m}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> yield(name: \"mean\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Carrier - $di",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "$carrier_m",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 2, "x": 0, "y": 16 },
     "repeat": "carrier_m",
     "targets": [
      {
       "query": "from(bucket: \"xr-1m\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\" or r[\"_field\"] == \"counter\"  )\r\n  |> filter(fn: (r) => r[\"di\"] == \"${di}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${carrier_m}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> yield(name: \"mean\")"
      }
     ]
    }
   ]
  },
  {
   "title": "DSC $di",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "$dsc_m",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 3, "x": 0, "y": 17 },
     "repeat": "dsc_m",
     "targets": [
      {
       "query": "from(bucket: \"xr-1m\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\" or r[\"_field\"] == \"counter\"  )\r\n  |> filter(fn: (r) => r[\"di\"] == \"${di}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${dsc_m}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    }
   ]
  },
  { "title": "Client PM $di", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 }, "repeat": "di" },
  {
   "title": "$client_m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 29 },
   "repeat": "client_m",
   "targets": [
    {
     "query": "from(bucket: \"xr-1m\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\" or r[\"_field\"] == \"counter\"  )\r\n  |> filter(fn: (r) => r[\"di\"] == \"${di}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${client_m}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "OTU - $di",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "repeat": "di",
   "collapsed": true,
   "panels": [
    {
     "title": "$otu_m",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 9 },
     "repeat": "odu_m",
     "targets": [
      {
       "query": "from(bucket: \"xr-1m\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\" or r[\"_field\"] == \"counter\"  )\r\n  |> filter(fn: (r) => r[\"di\"] == \"${di}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /otu/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> yield(name: \"mean\")"
      }
     ]
    }
   ]
  },
  {
   "title": "ODU $di ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 },
   "repeat": "di",
   "collapsed": true,
   "panels": [
    {
     "title": "$odu_m",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
     "repeat": "odu_m",
     "targets": [
      {
       "query": "from(bucket: \"xr-1m\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\" or r[\"_field\"] == \"counter\"  )\r\n  |> filter(fn: (r) => r[\"di\"] == \"${di}\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /odu/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> yield(name: \"mean\")"
      }
     ]
    }
   ]
  }
 ]
}