{
 "title": "ModuleReport",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "metrics",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.measurements(bucket: \"xr-1m\")"
   },
   {
    "name": "attributes",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagKeys(bucket: \"xr-1m\")"
   },
   {
    "name": "di",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(bucket: \"xr-1m\", tag: \"di\")"
   },
   {
    "name": "metrics_2",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.measurements(bucket: \"xr-1m\")"
   }
  ]
 },
 "panels": [
  { "title": "Device Id: $di", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "di" },
  {
   "title": "Measurement $metrics",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"xr-1m\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\" or r[\"_field\"] == \"counter\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^${metrics:regex}/)\r\n    |> filter(fn: (r) => r[\"di\"] =~ /^${di:regex}/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n      |> pivot(rowKey: [\"_time\"], columnKey: [\"_measurement\"], valueColumn: \"_value\")\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Table $metrics",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"xr-1m\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\" or r[\"_field\"] == \"counter\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^${metrics:regex}/)\r\n    |> filter(fn: (r) => r[\"di\"] =~ /^${di:regex}/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n      |> pivot(rowKey: [\"_time\"], columnKey: [\"_measurement\"], valueColumn: \"_value\")\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "DSC",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"xr-1m\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\")\r\n    |> filter(fn: (r) => r[\"_measurement\"] == \"xr.dsc.1m.osnr_rx_ne_avg\")\r\n  |> filter(fn: (r) => r[\"di\"] == \"${di}\")\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "DSC",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"xr-1m\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /${metrics_2:regex}/)\r\n  |> filter(fn: (r) => r[\"di\"] == \"${di}\")\r\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}