{
 "title": "Network Inventory",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "network",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(bucket: \"xr-1m\", tag: \"network\")"
   }
  ]
 },
 "panels": [
  {
   "title": "# of devices",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(bucket: \"xr-1m\", tag: \"sn\")\r\n|>count()"
    }
   ]
  },
  {
   "title": "Device Inventory - $network",
   "type": "table",
   "gridPos": { "h": 16, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "query": "  import \"math\"\r\nXR_LINE_TEMP_MIN = -5\r\nXR_LINE_TEMP_MAX = 75\r\nfrom(bucket: \"xr-1m\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"xr.lineptp.case_temp\")\r\n  |> filter(fn: (r) => r[\"network\"] == \"${network}\")\r\n  |> last()\r\n\r\n  |> pivot(rowKey:[\"di\"], columnKey: [\"_measurement\"], valueColumn: \"_value\")\r\n  |> rename(columns: {\"xr.lineptp.case_temp\": \"case_temp\"})    \r\n  |> map(fn: (r) => ({ r with Line_Temp_IN_RANGE : if math.abs(x: r.case_temp) <= XR_LINE_TEMP_MAX and math.abs(x: r.case_temp) >= XR_LINE_TEMP_MIN then true else false }))\r\n  |> keep(columns: [\"di\", \"sn\", \"role\", \"Line_Temp_IN_RANGE\"])  \r\n"
    },
    {
     "query": "import \"math\"\r\nXR_LINE_LASER_TEMP_MIN = 35\r\nXR_LINE_LASET_TEMP_MAX = 65\r\nfrom(bucket: \"xr-1m\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"xr.lineptp.laser_temp\")\r\n  |> last()\r\n   |> filter(fn: (r) => r[\"network\"] == \"${network}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_measurement\"], valueColumn: \"_value\")\r\n  |> rename(columns: {\"xr.lineptp.laser_temp\": \"laser_temp\"})    \r\n  |> map(fn: (r) => ({ r with Laser_Temp_IN_RANGE : if math.abs(x: r.laser_temp) <= XR_LINE_LASET_TEMP_MAX and math.abs(x: r.laser_temp) >= XR_LINE_LASER_TEMP_MIN then true else false }))\r\n    |> keep(columns: [\"di\", \"sn\", \"Laser_Temp_IN_RANGE\"])  \r\n"
    },
    {
     "query": "// (\"xr.lineptp.opt\" >= -18 and <= 4) and\r\n\r\nimport \"math\"\r\nXR_LINE_OPT_MIN = -18\r\nXR_LINE_OPT_MAX = 4\r\nfrom(bucket: \"xr-1m\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"xr.lineptp.opt_tx_ne\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n   |> filter(fn: (r) => r[\"network\"] == \"${network}\")\r\n  |> last()\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_measurement\"], valueColumn: \"_value\")\r\n  |> rename(columns: {\"xr.lineptp.opt_tx_ne\": \"lineptp_opt_tx_ne\"})    \r\n  |> map(fn: (r) => ({ r with Line_OPT_IN_RANGE : if math.abs(x: r.lineptp_opt_tx_ne) <= XR_LINE_OPT_MAX and math.abs(x: r.lineptp_opt_tx_ne) >= XR_LINE_OPT_MIN then true else false }))\r\n    |> keep(columns: [\"di\", \"sn\", \"Line_OPT_IN_RANGE\"])  \r\n       "
    },
    {
     "query": "// (\"xr.lineptp.opr\" >= -16 and <= 4)\r\nimport \"math\"\r\nXR_LINE_OPR_MIN = -18\r\nXR_LINE_OPR_MAX = 4\r\nfrom(bucket: \"xr-1m\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"xr.lineptp.opr_rx_ne\")\r\n   |> filter(fn: (r) => r[\"network\"] == \"${network}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> last()\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_measurement\"], valueColumn: \"_value\")\r\n  |> rename(columns: {\"xr.lineptp.opr_rx_ne\": \"lineptp_opr_rx_ne\"})    \r\n  |> map(fn: (r) => ({ r with Line_OPR_IN_RANGE : if math.abs(x: r.lineptp_opr_rx_ne) <= XR_LINE_OPR_MAX and math.abs(x: r.lineptp_opr_rx_ne) >= XR_LINE_OPR_MIN then true else false }))\r\n    |> keep(columns: [\"di\", \"sn\", \"_time\", \"Line_OPR_IN_RANGE\"])\r\n"
    },
    {
     "query": "dsc_nc_threshold = 0\r\ndsc_pd_threshold = .25\r\ndsc_na_threshold = 0.144742\r\n\r\ndata = from(bucket: \"xr-1m\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\")\r\n  |> filter(fn: (r) => r[\"network\"] == \"${network}\")\r\n\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"xr.dsc.pre_fec_ber_rx_ne\")\r\n    |> last()   \r\n     |> group(columns: [\"di\", \"_measurement\"])\r\n    |> reduce(\r\n                identity: {dsc_not_configured: 0.0, dsc_ok:0.0, dsc_power_down:0.0, dsc_not_acquired:0.0 },\r\n                fn: (r, accumulator) => ({\r\n                    dsc_not_configured: if r._value == dsc_nc_threshold then\r\n                        accumulator.dsc_not_configured + 1.0\r\n                    else\r\n                        accumulator.dsc_not_configured + 0.0,\r\n                    dsc_power_down: if r._value == dsc_pd_threshold then\r\n                        accumulator.dsc_power_down + 1.0\r\n                    else\r\n                        accumulator.dsc_power_down + 0.0,\r\n                    dsc_not_acquired: if r._value == dsc_na_threshold then\r\n                        accumulator.dsc_not_acquired + 1.0\r\n                    else\r\n                        accumulator.dsc_not_acquired + 0.0,\r\n                    dsc_ok : if (r._value != dsc_nc_threshold and r._value != dsc_pd_threshold and r._value != dsc_na_threshold) then\r\n                        accumulator.dsc_ok + 1.0\r\n                    else\r\n                        accumulator.dsc_power_down + 0.0,\r\n                }),\r\n   )\r\n  \r\n |> keep(columns: [\"network\", \"di\", \"sn\", \"dsc_not_acquired\", \"dsc_not_configured\", \"dsc_ok\", \"dsc_power_down\"])\r\n\r\n   |> yield(name: \"dsc_state\")    "
    }
   ]
  },
  {
   "title": "Device Inventory",
   "type": "table",
   "gridPos": { "h": 16, "w": 4, "x": 0, "y": 3 },
   "targets": [
    {
     "query": "from(bucket: \"xr-1m\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /case_temp/)\r\n  |> filter(fn:(r) => r[\"_field\"] == \"gauge\")\r\n  |> last()\r\n  |> group(columns: [\"network\"], mode:\"by\")\r\n  |> count()\r\n"
    }
   ]
  }
 ]
}