{
 "title": "Real-time PMs - Last 1min - N Records",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "sn",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(bucket: \"xr-1m\", tag: \"sn\")"
   },
   {
    "name": "di",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(bucket: \"xr-1m\", tag: \"di\")"
   },
   {
    "name": "aids",
    "query": " XR-L1-C1-DSC1, XR-L1-C1-DSC2, XR-L1-C1-DSC3, XR-L1-C1-DSC4, XR-L1-C1-DSC5, XR-L1-C1-DSC6, XR-L1-C1-DSC7, XR-L1-C1-DSC8, XR-L1-C1-DSC9, XR-L1-C1-DSC10, XR-L1-C1-DSC11, XR-L1-C1-DSC12, XR-L1-C1-DSC13, XR-L1-C1-DSC14, XR-L1-C1-DSC15, XR-L1-C1-DSC16, 1-1-1,1-1-2,1-1-3,1-1-4,1-1-5,1-1-6,1-1-7,1-1-8,1, 1-1"
   },
   { "name": "records", "query": "1, 5, 10, 15, 20, 25" },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "metrics",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.measurements(bucket: \"xr-1m\")"
   },
   {
    "name": "attributes",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagKeys(bucket: \"xr-1m\")"
   },
   {
    "name": "metrics_2",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.measurements(bucket: \"xr-1m\")"
   }
  ]
 },
 "panels": [
  { "title": "Module, Carrier PMs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Module PMs",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"xr-1m\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\")\r\n  |> filter(fn: (r) => r[\"rt\"] == \"lineptp\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] !~ /_min/ and r[\"_measurement\"] !~ /_max/ and r[\"_measurement\"] !~ /_avg/)\r\n  |> filter(fn: (r) => r[\"sn\"] =~ /^${sn:regex}$/)\r\n  |> filter(fn: (r) => r[\"di\"] =~ /^${di:regex}$/)\r\n  |> sort(columns: [\"_time\"], desc: true)\r\n  |> limit (n:${records})\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_measurement\"], valueColumn: \"_value\")\r\n "
    }
   ]
  },
  {
   "title": "Carrier PMs",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"xr-1m\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\")\r\n  |> filter(fn: (r) => r[\"rt\"] == \"carrier\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] !~ /_min/ and r[\"_measurement\"] !~ /_max/ and r[\"_measurement\"] !~ /_avg/)\r\n  |> filter(fn: (r) => r[\"sn\"] =~ /^${sn:regex}/)\r\n  |> filter(fn: (r) => r[\"di\"] =~ /^${di:regex}/)\r\n  |> sort(columns: [\"_time\"], desc: true)\r\n  |> limit (n:${records})\r\n  |> pivot(rowKey: [\"_time\", \"aid\"], columnKey: [\"_measurement\"], valueColumn: \"_value\")\r\n \r\n\r\n"
    }
   ]
  },
  {
   "title": "DSC PMs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "DSC PMs",
     "type": "table",
     "gridPos": { "h": 8, "w": 22, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "from(bucket: \"xr-1m\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\")\r\n  |> filter(fn: (r) => r[\"rt\"] == \"dsc\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] !~ /_min/ and r[\"_measurement\"] !~ /_max/ and r[\"_measurement\"] !~ /_avg/)\r\n  |> filter(fn: (r) => r[\"sn\"] =~ /^${sn:regex}/)\r\n  |> filter(fn: (r) => r[\"di\"] =~ /^${di:regex}/)\r\n  |> filter(fn: (r) => r[\"aid\"] =~ /^${aids:regex}$/)\r\n  |> sort(columns: [\"_time\"], desc: true)\r\n  |> limit (n:${records})\r\n  |> pivot(rowKey: [\"_time\", \"aid\"], columnKey: [\"_measurement\"], valueColumn: \"_value\")\r\n  |> map(      \r\n    fn: (r) => ({r with\r\n        \"DSC State\": if r._value == 0 then \"not configured\"\r\n        else if r._value == .25 then \"powered down\"\r\n        else if r._value == 0.144742 then \"not acquired\"\r\n        else \"ok\"\r\n\r\n    }))\r\n\r\n\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "OTN PMs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "OTU PMs",
     "type": "table",
     "gridPos": { "h": 8, "w": 22, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "from(bucket: \"xr-1m\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\" or r[\"_field\"] == \"counter\")\r\n  |> filter(fn: (r) => r[\"rt\"] == \"otu\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] !~ /_min/ and r[\"_measurement\"] !~ /_max/ and r[\"_measurement\"] !~ /_avg/)\r\n  |> filter(fn: (r) => r[\"sn\"] =~ /^${sn:regex}/)\r\n  |> filter(fn: (r) => r[\"di\"] =~ /^${di:regex}/)\r\n  |> sort(columns: [\"_time\"], desc: true)\r\n  |> limit (n:${records})\r\n  |> pivot(rowKey: [\"_time\", \"aid\"], columnKey: [\"_measurement\"], valueColumn: \"_value\")\r\n\r\n\r\n\r\n"
      }
     ]
    },
    {
     "title": "ODU PMs",
     "type": "table",
     "gridPos": { "h": 8, "w": 22, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "from(bucket: \"xr-1m\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\" or r[\"_field\"] == \"counter\")\r\n  |> filter(fn: (r) => r[\"rt\"] == \"odu\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] !~ /_min/ and r[\"_measurement\"] !~ /_max/ and r[\"_measurement\"] !~ /_avg/)\r\n  |> filter(fn: (r) => r[\"sn\"] =~ /^${sn:regex}/)\r\n  |> filter(fn: (r) => r[\"di\"] =~ /^${di:regex}/)\r\n  |> sort(columns: [\"_time\"], desc: true)\r\n  |> limit (n:${records})\r\n  |> pivot(rowKey: [\"_time\", \"aid\"], columnKey: [\"_measurement\"], valueColumn: \"_value\")\r\n\r\n\r\n\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Client PMs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "GigE Client PMs",
     "type": "table",
     "gridPos": { "h": 8, "w": 22, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "from(bucket: \"xr-1m\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\" or r[\"_field\"] == \"counter\")\r\n  |> filter(fn: (r) => r[\"rt\"] == \"clientptp\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] !~ /_min/ and r[\"_measurement\"] !~ /_max/ and r[\"_measurement\"] !~ /_avg/)\r\n  |> filter(fn: (r) => r[\"sn\"] =~ /^${sn:regex}/)\r\n  |> filter(fn: (r) => r[\"di\"] =~ /^${di:regex}/)\r\n  |> sort(columns: [\"_time\"], desc: true)\r\n  |> limit (n:${records})\r\n  |> pivot(rowKey: [\"_time\", \"aid\"], columnKey: [\"_measurement\"], valueColumn: \"_value\")\r\n\r\n\r\n\r\n"
      }
     ]
    }
   ]
  }
 ]
}