# /*
#  * Copyright 2022 Google LLC. 
#  * 
#  * This software is provided as-is, without warranty or representation for any use or purpose. 
#  * Your use of it is subject to your agreement with Google.
#  */
steps:
  - name: '${_PRE_REQ_REGION}-docker.pkg.dev/$PROJECT_ID/saas-cloud-build/saas-cloud-build-${_PREFIX}:latest'
    dir: gcp-deployment/single-tenant/terraform/env/saas/global/cloud-build-with-branch-template
    entrypoint: 'bash'
    env:
      - "_CUSTOMER_NAME=${_CUSTOMER_NAME}"
      - "_PREFIX=${_PREFIX}"
      - "_LB_TYPE=${_LB_TYPE}"
      - "_APIGEE=${_APIGEE}"
    args:
    - '-c'
    - |
      git checkout -b ${_CUSTOMER_NAME}
      if [ "${_LB_TYPE}" = "http" ] && [ "${_APIGEE}" = "false" ]; then
        sed -e "s/CUSTOMER_NAME/${_CUSTOMER_NAME}/g" -e "s/PREFIX/${_PREFIX}/g" -e "s/FUNCTION_URI/`echo $$_CLOUD_FUNCTION_URI | sed 's#https://##'`/g" init-script.sh.tpl > init-script.sh;
        sh init-script.sh
        rm -rf init-script.sh
      elif [ "${_LB_TYPE}" = "http" ] && [ "${_APIGEE}" = "true" ]; then
        sed -e "s/CUSTOMER_NAME/${_CUSTOMER_NAME}/g" -e "s/PREFIX/${_PREFIX}/g" -e "s/FUNCTION_URI/`echo $$_CLOUD_FUNCTION_URI | sed 's#https://##'`/g" appigee-init.sh.tpl > appigee-init.sh;
        sh appigee-init.sh
        rm -rf appigee-init.sh
      else
        sed -e "s/CUSTOMER_NAME/${_CUSTOMER_NAME}/g" -e "s/FUNCTION_URI/`echo $$_CLOUD_FUNCTION_URI | sed 's#https://##'`/g" -e "s/PREFIX/${_PREFIX}/g" init-tcp-script.sh.tpl > init-tcp-script.sh;
        sh init-tcp-script.sh
        rm -rf init-tcp-script.sh
      fi
    secretEnv: ['_CLOUD_FUNCTION_URI']

  - name: '${_PRE_REQ_REGION}-docker.pkg.dev/$PROJECT_ID/saas-cloud-build/saas-cloud-build-${_PREFIX}:latest'
    dir: gcp-deployment/single-tenant/terraform/env/saas/global/cloud-build-with-branch-template
    entrypoint: 'bash'
    env:
      - "_CUSTOMER_NAME=${_CUSTOMER_NAME}"
      - "_APIGEE=${_APIGEE}"
    args:
    - '-c'
    - |
      if [ "${_LB_TYPE}" = "http"  && [ "${_APIGEE}" = "false" ]; then
        sed -e "s/BUILD_PROJECT_ID/$PROJECT_ID/g" -e "s/BUILD_ID/$BUILD_ID/g" -e "s/CUSTOMER_NAME/${_CUSTOMER_NAME}/g" -e "s/FUNCTION_URI/`echo $$_CLOUD_FUNCTION_URI | sed 's#https://##'`/g" script.sh.tpl > script.sh;
        sh script.sh
        rm -rf script.sh
      elif [ "${_LB_TYPE}" = "http"  && [ "${_APIGEE}" = "true" ]; then
        sed -e "s/BUILD_PROJECT_ID/$PROJECT_ID/g" -e "s/BUILD_ID/$BUILD_ID/g" -e "s/CUSTOMER_NAME/${_CUSTOMER_NAME}/g" -e "s/FUNCTION_URI/`echo $$_CLOUD_FUNCTION_URI | sed 's#https://##'`/g" appigee.sh.tpl > appigee.sh;
        sh appigee.sh
        rm -rf appigee.sh
      else
        sed -e "s/BUILD_PROJECT_ID/$PROJECT_ID/g" -e "s/BUILD_ID/$BUILD_ID/g" -e "s/CUSTOMER_NAME/${_CUSTOMER_NAME}/g" -e "s/FUNCTION_URI/`echo $$_CLOUD_FUNCTION_URI | sed 's#https://##'`/g" script-tcp.sh.tpl > script-tcp.sh;
        sh script-tcp.sh
        rm -rf script-tcp.sh
      fi
    secretEnv: ['_CLOUD_FUNCTION_URI']
    
  - name: '${_PRE_REQ_REGION}-docker.pkg.dev/$PROJECT_ID/saas-cloud-build/saas-cloud-build-${_PREFIX}:latest'
    id: Remove Directory cloud build
    entrypoint: 'bash'
    env:
      - "_CUSTOMER_NAME=${_CUSTOMER_NAME}"
      - "_CUSTOMER_EMAIL=${_CUSTOMER_EMAIL}"
      - "_BRANCH_NAME=${_CUSTOMER_NAME}"
    args:
    - '-eEuo'
    - 'pipefail'
    - '-c'
    - |-
      sed  -e "s/CUSTOMER_NAME/${_CUSTOMER_NAME}/g" gcp-deployment/single-tenant/terraform/env/saas/global/cloud-build-with-branch-template/setup.py.tpl > gcp-deployment/single-tenant/terraform/env/saas/global/cloud-build-with-branch-template/setup.py;
      python3 gcp-deployment/single-tenant/terraform/env/saas/global/cloud-build-with-branch-template/setup.py 
      git add .
      if [ -n "$(git status --porcelain)" ]; then
        echo "There are changes";
        git config --global user.email "${_CUSTOMER_EMAIL}"
        git config --global user.name "${_CUSTOMER_NAME}"
        git commit -m "client ${_CUSTOMER_NAME}'s build trigger deleted"
        git push --set-upstream origin ${_CUSTOMER_NAME}
      else
        echo "No changes are there";
        exit
      fi

  - name: "${_PRE_REQ_REGION}-docker.pkg.dev/$PROJECT_ID/saas-cloud-build/saas-cloud-build-${_PREFIX}:latest"
    entrypoint: "bash"
    env:
      - "_CUSTOMER_NAME=${_CUSTOMER_NAME}"
      - "_CUSTOMER_EMAIL=${_CUSTOMER_EMAIL}"
      - "_REGION=${_REGION}"
      - "_CSR_TERRAFORM_REPO_NAME=${_CSR_TERRAFORM_REPO_NAME}"
      - "_TF_STATE_BUCKET_NAME=${_TF_STATE_BUCKET_NAME}"
      - "_LOG_BUCKET_NAME=${_LOG_BUCKET_NAME}"
      - "_CSR_APP_REPO_NAME=${_CSR_APP_REPO_NAME}"
      - "_PREFIX=${_PREFIX}"
      - "_SEED_PROJECT_ID=${_SEED_PROJECT_ID}"
      - "_ENTERPRISE_PROJECT_ID=${_ENTERPRISE_PROJECT_ID}"
      - "_ENTERPRISE_FOLDER_NAME=${_ENTERPRISE_FOLDER_NAME}"
      - "_BRANCH_NAME=${_CUSTOMER_NAME}"
      - "_TENANT_ID=${_TENANT_ID}"
      - "_MASTER_IP=${_MASTER_IP}"
      - "_SUBNET_IP=${_SUBNET_IP}"
      - "_POD_RANGE=${_POD_RANGE}"
      - "_SVC_RANGE=${_SVC_RANGE}"
      - "_MACHINE_TYPE=${_MACHINE_TYPE}"
      - "_ZONE=${_ZONE}"
      - "_MIN_COUNT=${_MIN_COUNT}"
      - "_MAX_COUNT=${_MAX_COUNT}"
      - "_NODE_COUNT=${_NODE_COUNT}"
      - "_ORG_LOGO_URL=${_ORG_LOGO_URL}"
      - "_LB_TYPE=${_LB_TYPE}"
      - "_PORT=${_PORT}"
      - "_TENANT_DOMAIN=${_TENANT_DOMAIN}"
      - "_PRE_REQ_REGION=${_PRE_REQ_REGION}"
      - "_TERRAFORM_CODE_BRANCH_NAME=${_TERRAFORM_CODE_BRANCH_NAME}"
      - "_VENDOR_EMAIL_ID=${_VENDOR_EMAIL_ID}"
      - "_APIGEE_REQUIRED=${_APIGEE}"
      - "_CMEK_KEY_PATH=${_KMS_KEY_PATH}"
      - "_ACCELERATOR_COUNT=${_ACCELERATOR_COUNT}"
      - "_ACCELERATOR_TYPE=${_ACCELERATOR_TYPE}"
    args:
      - "-eEuo"
      - "pipefail"
      - "-c"
      - |-
        git config --global user.email "${_CUSTOMER_EMAIL}"
        git config --global user.name "${_CUSTOMER_NAME}"
        mkdir -p gcp-deployment/single-tenant/terraform/env/saas/global/${_CUSTOMER_NAME}-cloud-build-with-branch/
        envsubst < gcp-deployment/single-tenant/terraform/env/saas/global/cloud-build-with-branch-template/triggers.tf.tpl > gcp-deployment/single-tenant/terraform/env/saas/global/${_CUSTOMER_NAME}-cloud-build-with-branch/triggers.tf
        for f in $(find gcp-deployment/single-tenant/terraform/env/saas/global/cloud-build-with-branch-template/ -regex '.*\.tf'); do envsubst < $f > "gcp-deployment/single-tenant/terraform/env/saas/global/${_CUSTOMER_NAME}-cloud-build-with-branch/$(basename $f)"; done
        git add .
        git commit -m "client ${_CUSTOMER_NAME}'s trigger code created"
        git push --set-upstream origin ${_CUSTOMER_NAME}

  - name: "hashicorp/terraform:1.0.7"
    dir: gcp-deployment/single-tenant/terraform/env/saas/global/${_CUSTOMER_NAME}-cloud-build-with-branch
    args:
      - "-c"
      - |
        terraform init
    id: terraform init
    entrypoint: sh
  - name: "hashicorp/terraform:1.0.7"
    dir: gcp-deployment/single-tenant/terraform/env/saas/global/${_CUSTOMER_NAME}-cloud-build-with-branch
    args:
      - "-c"
      - |
        terraform fmt
    id: terraform fmt
    entrypoint: sh
  - name: "hashicorp/terraform:1.0.7"
    dir: gcp-deployment/single-tenant/terraform/env/saas/global/${_CUSTOMER_NAME}-cloud-build-with-branch
    args:
      - "-c"
      - |
        terraform validate
    id: terraform validate
    entrypoint: sh
  - name: "hashicorp/terraform:1.0.7"
    dir: gcp-deployment/single-tenant/terraform/env/saas/global/${_CUSTOMER_NAME}-cloud-build-with-branch
    args:
      - "-c"
      - |
        terraform plan
    id: terraform plan
    entrypoint: sh
  - name: "hashicorp/terraform:1.0.7"
    dir: gcp-deployment/single-tenant/terraform/env/saas/global/${_CUSTOMER_NAME}-cloud-build-with-branch
    args:
      - "-c"
      - |
        terraform apply -input=false -auto-approve
    id: terraform apply
    entrypoint: sh

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['alpha', 'builds', 'triggers', 'run', '${_CUSTOMER_NAME}-single-tenant-secret-create-saas-trigger', '--branch=${_CUSTOMER_NAME}', '--region=${_REGION}']
    id: 'trigger next build'

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_NUMBER/secrets/${_PREFIX}_CLOUD_FUNCTION_URI/versions/latest
    env: _CLOUD_FUNCTION_URI

logsBucket: 'gs://${_LOG_BUCKET_NAME}'
options:
  logging: GCS_ONLY
