apiVersion: v1
kind: Service
metadata:
  name: {{ include "DomainManager.ndu-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
      {{- include "DomainManager.labels" . | nindent 4 }}
      {{- with .Values.ndus.service.labels }}
      {{- . | toYaml | nindent 4 }}
      {{- end }}
spec:
  type: {{ .Values.ndus.service.type | default "ClusterIP" }}
  ports:
    - name: ndus-port
      port: {{ .Values.ndus.port | default "8080" }}
      targetPort: ndus-port
  selector:
   {{- include "DomainManager.ndu-service.selectorLabels" . | nindent 4 }}