apiVersion: v1
kind: Service
metadata:
  name: {{ include "DomainManager.transport-capacity.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
      {{- include "DomainManager.labels" . | nindent 4 }}
      {{- with .Values.tc.service.labels }}
      {{- . | toYaml | nindent 4 }}
      {{- end }}
spec:
  type: {{ .Values.tc.service.type | default "ClusterIP" }}
  ports:
  - name: tc-port
    port: {{ .Values.tc.port | default "8080" }}
    targetPort: tc-port
  selector:
   {{- include "DomainManager.transport-capacity.selectorLabels" . | nindent 4 }}