apiVersion: v1
kind: Secret
metadata:
  name: ipm-postgresql-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "5"
type: Opaque
data:
  postgres_password: {{ .Values.global.postgres.postgres_password }}
  password: {{ .Values.global.postgres.password }}
  replication_password: {{ .Values.global.postgres.replication_password }}

