# /*
#  * Copyright 2022 Google LLC. 
#  * 
#  * This software is provided as-is, without warranty or representation for any use or purpose. 
#  * Your use of it is subject to your agreement with Google.
#  */
steps:
  - name: "hashicorp/terraform:1.0.7"
    dir: gcp-deployment/terraform/env/saas/global/custom-monitoring/metrics_scope
    args:
      - "-c"
      - |
        sed -e "s/TF_STATE_BUCKET_NAME/${_TF_STATE_BUCKET_NAME}/g" -e "s/PREFIX_NAME/${_PREFIX}/g" backend.tf.tpl > backend.tf
        sed -e "s/HOST_PROJECT_ID/$$HOST_PROJECT_ID/g" -e "s/_FREEMIUM_PROJECT_ID/$$_FREEMIUM_PROJECT_ID/g" terraform.tfvars.tpl > terraform.tfvars
    id: generate terraform manifests
    entrypoint: sh
    secretEnv: ['_FREEMIUM_PROJECT_ID','HOST_PROJECT_ID']

  - name: "hashicorp/terraform:1.0.7"
    dir: gcp-deployment/terraform/env/saas/global/custom-monitoring/metrics_scope
    args:
      - "-c"
      - |
        terraform init
    id: terraform init
    entrypoint: sh

  - name: "hashicorp/terraform:1.0.7"
    dir: gcp-deployment/terraform/env/saas/global/custom-monitoring/metrics_scope
    args:
      - "-c"
      - |
        terraform fmt
    id: terraform fmt
    entrypoint: sh

  - name: "hashicorp/terraform:1.0.7"
    dir: gcp-deployment/terraform/env/saas/global/custom-monitoring/metrics_scope
    args:
      - "-c"
      - |
        terraform validate
    id: terraform validate
    entrypoint: sh

  - name: "hashicorp/terraform:1.0.7"
    dir: gcp-deployment/terraform/env/saas/global/custom-monitoring/metrics_scope
    args:
      - "-c"
      - |
        terraform plan
    id: terraform plan
    entrypoint: sh

  - name: "hashicorp/terraform:1.0.7"
    dir: gcp-deployment/terraform/env/saas/global/custom-monitoring/metrics_scope
    args:
      - "-c"
      - |
        terraform apply -input=false -auto-approve
    id: terraform apply
    entrypoint: sh
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['alpha', 'builds', 'triggers', 'run', 'custom-dashboard-${_PREFIX}-trigger', '--branch=${_BRANCH_NAME}']
    id: 'trigger next build'

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_NUMBER/secrets/${_PREFIX}_FREEMIUM_PROJECT_ID/versions/latest
    env: _FREEMIUM_PROJECT_ID
  - versionName: projects/$PROJECT_NUMBER/secrets/${_PREFIX}_HOST_PROJECT_ID/versions/latest
    env: HOST_PROJECT_ID

logsBucket: 'gs://${_LOG_BUCKET_NAME}'
options:
  logging: GCS_ONLY
